" common set
set viminfofile=NONE
if isdirectory(expand("~/.vimtmp"))
set backupdir=~/.vimtmp
set directory=~/.vimtmp
endif
set number
set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set cindent
" t mouse=nich
" t mouse=a
set colorcolumn=79
set cursorline
set autowrite
set hlsearch
set incsearch
set nobackup
set nowrap
set foldenable
set foldmethod=syntax
set foldlevel=99
set fileencodings=utf-8,gbk
let mapleader=';'

" vbundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" nerdtree
Plugin 'scrooloose/nerdtree'
let NERDTreeWinSize=30
let NERDTreeHighlightCursorline=1
let NERDTreeMinimalUI=1
map <F11> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" tagbar
Plugin 'majutsushi/tagbar'
let g:tagbar_width=30
let g:tagbar_autofocus=1
let g:tagbar_compact=1
map <F12> :TagbarToggle<CR>

" vim-fugitive
Plugin 'tpope/vim-fugitive'

" vim-airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
set laststatus=2
let g:airline_theme="wombat"
let g:airline_powerline_fonts=1 
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#buffer_nr_show=1
let g:airline#extensions#tabline#formatter='unique_tail'
let g:airline#extensions#whitespace#enabled=0
if !exists('g:airline_symbols')
    let g:airline_symbols={}
endif
" let g:airline_symbols.linenr='LN'
let g:airline_symbols.maxlinenr=''

" Visual-Mark
Plugin 'vim-scripts/Visual-Mark'

" hexmode
Plugin 'fidian/hexmode'

" molokai
Plugin 'tomasr/molokai'

" vim-colors-solarized
Plugin 'altercation/vim-colors-solarized'

" vim-cpp-enhanced-higlight
Plugin 'octol/vim-cpp-enhanced-highlight'
let g:cpp_class_scope_highlight=1
let g:cpp_experimental_template_highlight=1
let g:cpp_concepts_highlight=1
let c_no_curly_error=1

" derekwyatt/vim-fswitch
Plugin 'derekwyatt/vim-fswitch'
nmap <silent> <Leader>oa :FSHere<cr>
nmap <silent> <Leader>or :FSSplitRight<cr>
nmap <silent> <Leader>ol :FSSplitLeft<cr>

" vimcdoc
Plugin 'vimchina/vimcdoc'

" vim-syntax-x86-objdump-d
Plugin 'shiracamus/vim-syntax-x86-objdump-d'

" vim-linux-coding-style
" Plugin 'vivien/vim-linux-coding-style'
" let g:linuxsty_patterns=[expand("~/OSCode/Linux/")]

" vim-dirdiff
Plugin 'will133/vim-dirdiff'

call vundle#end()
filetype plugin indent on

syntax on
colorscheme molokai
" lorscheme solarized

" ctags
set tags=tags,./tags,~/.tags/include.tags

" cscope
set csto=0
set cst
" t cspc=3
set csverb
if filereadable(expand("~/.cscope/include.cscope"))
    cs add ~/.cscope/include.cscope
endif
if filereadable(".cscope.out")
    cs add .cscope.out
endif
set nocsverb

iab /// //////////////////////////////////////////////////////////////////////////////<CR><BS><BS>
